using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Y.Core.Enum
{
    /// <summary>
    /// FontAwesome图标枚举
    /// </summary>
    public enum FaEnum
    {
        fa_glass = 61440,
        fa_music,
        fa_search,
        fa_envelope_o,
        fa_heart,
        fa_star,
        fa_star_o,
        fa_user,
        fa_film,
        fa_th_large,
        fa_th,
        fa_th_list,
        fa_check,
        fa_times,
        fa_remove = 61453,
        fa_close = 61453,
        fa_search_plus,
        fa_search_minus = 61456,
        fa_power_off,
        fa_signal,
        fa_cog,
        fa_gear = 61459,
        fa_trash_o,
        fa_home,
        fa_file_o,
        fa_clock_o,
        fa_road,
        fa_download,
        fa_arrow_circle_o_down,
        fa_arrow_circle_o_up,
        fa_inbox,
        fa_play_circle_o,
        fa_repeat,
        fa_rotate_right = 61470,
        fa_refresh = 61473,
        fa_list_alt,
        fa_lock,
        fa_flag,
        fa_headphones,
        fa_volume_off,
        fa_volume_down,
        fa_volume_up,
        fa_qrcode,
        fa_barcode,
        fa_tag,
        fa_tags,
        fa_book,
        fa_bookmark,
        fa_print,
        fa_camera,
        fa_font,
        fa_bold,
        fa_italic,
        fa_text_height,
        fa_text_width,
        fa_align_left,
        fa_align_center,
        fa_align_right,
        fa_align_justify,
        fa_list,
        fa_outdent,
        fa_dedent = 61499,
        fa_indent,
        fa_video_camera,
        fa_picture_o,
        fa_photo = 61502,
        fa_image = 61502,
        fa_pencil = 61504,
        fa_map_marker,
        fa_adjust,
        fa_tint,
        fa_pencil_square_o,
        fa_edit = 61508,
        fa_share_square_o,
        fa_check_square_o,
        fa_arrows,
        fa_step_backward,
        fa_fast_backward,
        fa_backward,
        fa_play,
        fa_pause,
        fa_stop,
        fa_forward,
        fa_fast_forward = 61520,
        fa_step_forward,
        fa_eject,
        fa_chevron_left,
        fa_chevron_right,
        fa_plus_circle,
        fa_minus_circle,
        fa_times_circle,
        fa_check_circle,
        fa_question_circle,
        fa_info_circle,
        fa_crosshairs,
        fa_times_circle_o,
        fa_check_circle_o,
        fa_ban,
        fa_arrow_left = 61536,
        fa_arrow_right,
        fa_arrow_up,
        fa_arrow_down,
        fa_share,
        fa_mail_forward = 61540,
        fa_expand,
        fa_compress,
        fa_plus,
        fa_minus,
        fa_asterisk,
        fa_exclamation_circle,
        fa_gift,
        fa_leaf,
        fa_fire,
        fa_eye,
        fa_eye_slash = 61552,
        fa_exclamation_triangle,
        fa_warning = 61553,
        fa_plane,
        fa_calendar,
        fa_random,
        fa_comment,
        fa_magnet,
        fa_chevron_up,
        fa_chevron_down,
        fa_retweet,
        fa_shopping_cart,
        fa_folder,
        fa_folder_open,
        fa_arrows_v,
        fa_arrows_h,
        fa_bar_chart = 61568,
        fa_bar_chart_o = 61568,
        fa_twitter_square,
        fa_facebook_square,
        fa_camera_retro,
        fa_key,
        fa_cogs,
        fa_gears = 61573,
        fa_comments,
        fa_thumbs_o_up,
        fa_thumbs_o_down,
        fa_star_half,
        fa_heart_o,
        fa_sign_out,
        fa_linkedin_square,
        fa_thumb_tack,
        fa_external_link,
        fa_sign_in = 61584,
        fa_trophy,
        fa_github_square,
        fa_upload,
        fa_lemon_o,
        fa_phone,
        fa_square_o,
        fa_bookmark_o,
        fa_phone_square,
        fa_twitter,
        fa_facebook,
        fa_facebook_f = 61594,
        fa_github,
        fa_unlock,
        fa_credit_card,
        fa_rss,
        fa_feed = 61598,
        fa_hdd_o = 61600,
        fa_bullhorn,
        fa_bell = 61683,
        fa_certificate = 61603,
        fa_hand_o_right,
        fa_hand_o_left,
        fa_hand_o_up,
        fa_hand_o_down,
        fa_arrow_circle_left,
        fa_arrow_circle_right,
        fa_arrow_circle_up,
        fa_arrow_circle_down,
        fa_globe,
        fa_wrench,
        fa_tasks,
        fa_filter = 61616,
        fa_briefcase,
        fa_arrows_alt,
        fa_users = 61632,
        fa_group = 61632,
        fa_link,
        fa_chain = 61633,
        fa_cloud,
        fa_flask,
        fa_scissors,
        fa_cut = 61636,
        fa_files_o,
        fa_copy = 61637,
        fa_paperclip,
        fa_floppy_o,
        fa_save = 61639,
        fa_square,
        fa_bars,
        fa_navicon = 61641,
        fa_reorder = 61641,
        fa_list_ul,
        fa_list_ol,
        fa_strikethrough,
        fa_underline,
        fa_table,
        fa_magic = 61648,
        fa_truck,
        fa_pinterest,
        fa_pinterest_square,
        fa_google_plus_square,
        fa_google_plus,
        fa_money,
        fa_caret_down,
        fa_caret_up,
        fa_caret_left,
        fa_caret_right,
        fa_columns,
        fa_sort,
        fa_unsorted = 61660,
        fa_sort_desc,
        fa_sort_down = 61661,
        fa_sort_asc,
        fa_sort_up = 61662,
        fa_envelope = 61664,
        fa_linkedin,
        fa_undo,
        fa_rotate_left = 61666,
        fa_gavel,
        fa_legal = 61667,
        fa_tachometer,
        fa_dashboard = 61668,
        fa_comment_o,
        fa_comments_o,
        fa_bolt,
        fa_flash = 61671,
        fa_sitemap,
        fa_umbrella,
        fa_clipboard,
        fa_paste = 61674,
        fa_lightbulb_o,
        fa_exchange,
        fa_cloud_download,
        fa_cloud_upload,
        fa_user_md = 61680,
        fa_stethoscope,
        fa_suitcase,
        fa_bell_o = 61602,
        fa_coffee = 61684,
        fa_cutlery,
        fa_file_text_o,
        fa_building_o,
        fa_hospital_o,
        fa_ambulance,
        fa_medkit,
        fa_fighter_jet,
        fa_beer,
        fa_h_square,
        fa_plus_square,
        fa_angle_double_left = 61696,
        fa_angle_double_right,
        fa_angle_double_up,
        fa_angle_double_down,
        fa_angle_left,
        fa_angle_right,
        fa_angle_up,
        fa_angle_down,
        fa_desktop,
        fa_laptop,
        fa_tablet,
        fa_mobile,
        fa_mobile_phone = 61707,
        fa_circle_o,
        fa_quote_left,
        fa_quote_right,
        fa_spinner = 61712,
        fa_circle,
        fa_reply,
        fa_mail_reply = 61714,
        fa_github_alt,
        fa_folder_o,
        fa_folder_open_o,
        fa_smile_o = 61720,
        fa_frown_o,
        fa_meh_o,
        fa_gamepad,
        fa_keyboard_o,
        fa_flag_o,
        fa_flag_checkered,
        fa_terminal = 61728,
        fa_code,
        fa_reply_all,
        fa_mail_reply_all = 61730,
        fa_star_half_o,
        fa_star_half_empty = 61731,
        fa_star_half_full = 61731,
        fa_location_arrow,
        fa_crop,
        fa_code_fork,
        fa_chain_broken,
        fa_unlink = 61735,
        fa_question,
        fa_info,
        fa_exclamation,
        fa_superscript,
        fa_subscript,
        fa_eraser,
        fa_puzzle_piece,
        fa_microphone = 61744,
        fa_microphone_slash,
        fa_shield,
        fa_calendar_o,
        fa_fire_extinguisher,
        fa_rocket,
        fa_maxcdn,
        fa_chevron_circle_left,
        fa_chevron_circle_right,
        fa_chevron_circle_up,
        fa_chevron_circle_down,
        fa_html5,
        fa_css3,
        fa_anchor,
        fa_unlock_alt,
        fa_bullseye = 61760,
        fa_ellipsis_h,
        fa_ellipsis_v,
        fa_rss_square,
        fa_play_circle,
        fa_ticket,
        fa_minus_square,
        fa_minus_square_o,
        fa_level_up,
        fa_level_down,
        fa_check_square,
        fa_pencil_square,
        fa_external_link_square,
        fa_share_square,
        fa_compass,
        fa_caret_square_o_down = 61776,
        fa_toggle_down = 61776,
        fa_caret_square_o_up,
        fa_toggle_up = 61777,
        fa_caret_square_o_right,
        fa_toggle_right = 61778,
        fa_eur,
        fa_euro = 61779,
        fa_gbp,
        fa_usd,
        fa_dollar = 61781,
        fa_inr,
        fa_rupee = 61782,
        fa_jpy,
        fa_cny = 61783,
        fa_rmb = 61783,
        fa_yen = 61783,
        fa_rub,
        fa_ruble = 61784,
        fa_rouble = 61784,
        fa_krw,
        fa_won = 61785,
        fa_btc,
        fa_bitcoin = 61786,
        fa_file,
        fa_file_text,
        fa_sort_alpha_asc,
        fa_sort_alpha_desc,
        fa_sort_amount_asc = 61792,
        fa_sort_amount_desc,
        fa_sort_numeric_asc,
        fa_sort_numeric_desc,
        fa_thumbs_up,
        fa_thumbs_down,
        fa_youtube_square,
        fa_youtube,
        fa_xing,
        fa_xing_square,
        fa_youtube_play,
        fa_dropbox,
        fa_stack_overflow,
        fa_instagram,
        fa_flickr,
        fa_adn = 61808,
        fa_bitbucket,
        fa_bitbucket_square,
        fa_tumblr,
        fa_tumblr_square,
        fa_long_arrow_down,
        fa_long_arrow_up,
        fa_long_arrow_left,
        fa_long_arrow_right,
        fa_apple,
        fa_windows,
        fa_android,
        fa_linux,
        fa_dribbble,
        fa_skype,
        fa_foursquare = 61824,
        fa_trello,
        fa_female,
        fa_male,
        fa_gratipay,
        fa_gittip = 61828,
        fa_sun_o,
        fa_moon_o,
        fa_archive,
        fa_bug,
        fa_vk,
        fa_weibo,
        fa_renren,
        fa_pagelines,
        fa_stack_exchange,
        fa_arrow_circle_o_right,
        fa_arrow_circle_o_left = 61840,
        fa_caret_square_o_left,
        fa_toggle_left = 61841,
        fa_dot_circle_o,
        fa_wheelchair,
        fa_vimeo_square,
        fa_try,
        fa_turkish_lira = 61845,
        fa_plus_square_o,
        fa_space_shuttle,
        fa_slack,
        fa_envelope_square,
        fa_wordpress,
        fa_openid,
        fa_university,
        fa_institution = 61852,
        fa_bank = 61852,
        fa_graduation_cap,
        fa_mortar_board = 61853,
        fa_yahoo,
        fa_google = 61856,
        fa_reddit,
        fa_reddit_square,
        fa_stumbleupon_circle,
        fa_stumbleupon,
        fa_delicious,
        fa_digg,
        fa_pied_piper_pp,
        fa_pied_piper_alt,
        fa_drupal,
        fa_joomla,
        fa_language,
        fa_fax,
        fa_building,
        fa_child,
        fa_paw = 61872,
        fa_spoon,
        fa_cube,
        fa_cubes,
        fa_behance,
        fa_behance_square,
        fa_steam,
        fa_steam_square,
        fa_recycle,
        fa_car,
        fa_automobile = 61881,
        fa_taxi,
        fa_cab = 61882,
        fa_tree,
        fa_spotify,
        fa_deviantart,
        fa_soundcloud,
        fa_database = 61888,
        fa_file_pdf_o,
        fa_file_word_o,
        fa_file_excel_o,
        fa_file_powerpoint_o,
        fa_file_image_o,
        fa_file_photo_o = 61893,
        fa_file_picture_o = 61893,
        fa_file_archive_o,
        fa_file_zip_o = 61894,
        fa_file_audio_o,
        fa_file_sound_o = 61895,
        fa_file_video_o,
        fa_file_movie_o = 61896,
        fa_file_code_o,
        fa_vine,
        fa_codepen,
        fa_jsfiddle,
        fa_life_ring,
        fa_life_bouy = 61901,
        fa_life_buoy = 61901,
        fa_life_saver = 61901,
        fa_support = 61901,
        fa_circle_o_notch,
        fa_rebel = 61904,
        fa_ra = 61904,
        fa_resistance = 61904,
        fa_empire,
        fa_ge = 61905,
        fa_git_square,
        fa_git,
        fa_hacker_news,
        fa_y_combinator_square = 61908,
        fa_yc_square = 61908,
        fa_tencent_weibo,
        fa_qq,
        fa_weixin,
        fa_wechat = 61911,
        fa_paper_plane,
        fa_send = 61912,
        fa_paper_plane_o,
        fa_send_o = 61913,
        fa_history,
        fa_circle_thin,
        fa_header,
        fa_paragraph,
        fa_sliders,
        fa_share_alt = 61920,
        fa_share_alt_square,
        fa_bomb,
        fa_futbol_o,
        fa_soccer_ball_o = 61923,
        fa_tty,
        fa_binoculars,
        fa_plug,
        fa_slideshare,
        fa_twitch,
        fa_yelp,
        fa_newspaper_o,
        fa_wifi,
        fa_calculator,
        fa_paypal,
        fa_google_wallet,
        fa_cc_visa = 61936,
        fa_cc_mastercard,
        fa_cc_discover,
        fa_cc_amex,
        fa_cc_paypal,
        fa_cc_stripe,
        fa_bell_slash,
        fa_bell_slash_o,
        fa_trash,
        fa_copyright,
        fa_at,
        fa_eyedropper,
        fa_paint_brush,
        fa_birthday_cake,
        fa_area_chart,
        fa_pie_chart = 61952,
        fa_line_chart,
        fa_lastfm,
        fa_lastfm_square,
        fa_toggle_off,
        fa_toggle_on,
        fa_bicycle,
        fa_bus,
        fa_ioxhost,
        fa_angellist,
        fa_cc,
        fa_ils,
        fa_shekel = 61963,
        fa_sheqel = 61963,
        fa_meanpath,
        fa_buysellads,
        fa_connectdevelop,
        fa_dashcube = 61968,
        fa_forumbee,
        fa_leanpub,
        fa_sellsy,
        fa_shirtsinbulk,
        fa_simplybuilt,
        fa_skyatlas,
        fa_cart_plus,
        fa_cart_arrow_down,
        fa_diamond,
        fa_ship,
        fa_user_secret,
        fa_motorcycle,
        fa_street_view,
        fa_heartbeat,
        fa_venus = 61985,
        fa_mars,
        fa_mercury,
        fa_transgender,
        fa_intersex = 61988,
        fa_transgender_alt,
        fa_venus_double,
        fa_mars_double,
        fa_venus_mars,
        fa_mars_stroke,
        fa_mars_stroke_v,
        fa_mars_stroke_h,
        fa_neuter,
        fa_genderless,
        fa_facebook_official = 62000,
        fa_pinterest_p,
        fa_whatsapp,
        fa_server,
        fa_user_plus,
        fa_user_times,
        fa_bed,
        fa_hotel = 62006,
        fa_viacoin,
        fa_train,
        fa_subway,
        fa_medium,
        fa_y_combinator,
        fa_yc = 62011,
        fa_optin_monster,
        fa_opencart,
        fa_expeditedssl,
        fa_battery_full = 62016,
        fa_battery_4 = 62016,
        fa_battery = 62016,
        fa_battery_three_quarters,
        fa_battery_3 = 62017,
        fa_battery_half,
        fa_battery_2 = 62018,
        fa_battery_quarter,
        fa_battery_1 = 62019,
        fa_battery_empty,
        fa_battery_0 = 62020,
        fa_mouse_pointer,
        fa_i_cursor,
        fa_object_group,
        fa_object_ungroup,
        fa_sticky_note,
        fa_sticky_note_o,
        fa_cc_jcb,
        fa_cc_diners_club,
        fa_clone,
        fa_balance_scale,
        fa_hourglass_o = 62032,
        fa_hourglass_start,
        fa_hourglass_1 = 62033,
        fa_hourglass_half,
        fa_hourglass_2 = 62034,
        fa_hourglass_end,
        fa_hourglass_3 = 62035,
        fa_hourglass,
        fa_hand_rock_o,
        fa_hand_grab_o = 62037,
        fa_hand_paper_o,
        fa_hand_stop_o = 62038,
        fa_hand_scissors_o,
        fa_hand_lizard_o,
        fa_hand_spock_o,
        fa_hand_pointer_o,
        fa_hand_peace_o,
        fa_trademark,
        fa_registered,
        fa_creative_commons,
        fa_gg = 62048,
        fa_gg_circle,
        fa_tripadvisor,
        fa_odnoklassniki,
        fa_odnoklassniki_square,
        fa_get_pocket,
        fa_wikipedia_w,
        fa_safari,
        fa_chrome,
        fa_firefox,
        fa_opera,
        fa_internet_explorer,
        fa_television,
        fa_tv = 62060,
        fa_contao,
        fa_500px,
        fa_amazon = 62064,
        fa_calendar_plus_o,
        fa_calendar_minus_o,
        fa_calendar_times_o,
        fa_calendar_check_o,
        fa_industry,
        fa_map_pin,
        fa_map_signs,
        fa_map_o,
        fa_map,
        fa_commenting,
        fa_commenting_o,
        fa_houzz,
        fa_vimeo,
        fa_black_tie,
        fa_fonticons = 62080,
        fa_reddit_alien,
        fa_edge,
        fa_credit_card_alt,
        fa_codiepie,
        fa_modx,
        fa_fort_awesome,
        fa_usb,
        fa_product_hunt,
        fa_mixcloud,
        fa_scribd,
        fa_pause_circle,
        fa_pause_circle_o,
        fa_stop_circle,
        fa_stop_circle_o,
        fa_shopping_bag = 62096,
        fa_shopping_basket,
        fa_hashtag,
        fa_bluetooth,
        fa_bluetooth_b,
        fa_percent,
        fa_gitlab,
        fa_wpbeginner,
        fa_wpforms,
        fa_envira,
        fa_universal_access,
        fa_wheelchair_alt,
        fa_question_circle_o,
        fa_blind,
        fa_audio_description,
        fa_volume_control_phone = 62112,
        fa_braille,
        fa_assistive_listening_systems,
        fa_american_sign_language_interpreting,
        fa_asl_interpreting = 62115,
        fa_deaf,
        fa_deafness = 62116,
        fa_hard_of_hearing = 62116,
        fa_glide,
        fa_glide_g,
        fa_sign_language,
        fa_signing = 62119,
        fa_low_vision,
        fa_viadeo,
        fa_viadeo_square,
        fa_snapchat,
        fa_snapchat_ghost,
        fa_snapchat_square,
        fa_pied_piper,
        fa_first_order = 62128,
        fa_yoast,
        fa_themeisle,
        fa_google_plus_official,
        fa_google_plus_circle = 62131,
        fa_font_awesome,
        fa_fa = 62132,
        fa_handshake_o,
        fa_envelope_open,
        fa_envelope_open_o,
        fa_linode,
        fa_address_book,
        fa_address_book_o,
        fa_address_card,
        fa_vcard = 62139,
        fa_address_card_o,
        fa_vcard_o = 62140,
        fa_user_circle,
        fa_user_circle_o,
        fa_user_o = 62144,
        fa_id_badge,
        fa_id_card,
        fa_drivers_license = 62146,
        fa_id_card_o,
        fa_drivers_license_o = 62147,
        fa_quora,
        fa_free_code_camp,
        fa_telegram,
        fa_thermometer_full,
        fa_thermometer_4 = 62151,
        fa_thermometer = 62151,
        fa_thermometer_three_quarters,
        fa_thermometer_3 = 62152,
        fa_thermometer_half,
        fa_thermometer_2 = 62153,
        fa_thermometer_quarter,
        fa_thermometer_1 = 62154,
        fa_thermometer_empty,
        fa_thermometer_0 = 62155,
        fa_shower,
        fa_bath,
        fa_bathtub = 62157,
        fa_s15 = 62157,
        fa_podcast,
        fa_window_maximize = 62160,
        fa_window_minimize,
        fa_window_restore,
        fa_window_close,
        fa_times_rectangle = 62163,
        fa_window_close_o,
        fa_times_rectangle_o = 62164,
        fa_bandcamp,
        fa_grav,
        fa_etsy,
        fa_imdb,
        fa_ravelry,
        fa_eercast,
        fa_microchip,
        fa_snowflake_o,
        fa_superpowers,
        fa_wpexplorer,
        fa_meetup = 62176
    }
}
